apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dbkeitest-tls
  namespace: bkextest
spec:
  secretName: dbkeitest-tls
  issuerRef:
    name: bke-ci-ecc-tr
    kind: ClusterIssuer
  commonName: dbkeitest.virtorch.brown.edu
  dnsNames:
  - dbkeitest.virtorch.brown.edu
