apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dbkeitest-vo
  namespace: cert-manager
spec:
  secretName: dbkeitest-tls
  issuerRef:
    name: bke-ci-eab
    kind: ClusterIssuer
  commonName: dbkeitest.virtorch.brown.edu
  dnsNames:
  - dbkeitest.virtorch.brown.edu
