apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bkeddrtest-vo
  namespace: cert-manager
spec:
  secretName: bkeddrtest-tls
  issuerRef:
    name: bke-ci-eab
    kind: ClusterIssuer
  commonName: drbkedtest.virtorch.brown.edu
  dnsNames:
  - drbkedtest.virtorch.brown.edu
