apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dbkedtest-vo
  namespace: cert-manager
spec:
  secretName: dbkedtest-tls
  issuerRef:
    name: bke-ci-eab
    kind: ClusterIssuer
  commonName: dbkedtest.virtorch.brown.edu
  dnsNames:
  - dbkedtest.virtorch.brown.edu
