
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /tmp/nginx.pid;


events {
    worker_connections  1024;
}


http {
    proxy_temp_path /tmp/proxy_temp;
    client_body_temp_path /tmp/client_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Trust these IP ranges as proxy headers
    set_real_ip_from 10.42.0.0/16;        # Internal load balancers
    set_real_ip_from 172.16.0.0/12;
    set_real_ip_from 192.168.0.0/16;
    set_real_ip_from 127.0.0.1;
    set_real_ip_from 10.4.25.231;
    set_real_ip_from 10.4.19.233;
    set_real_ip_from 10.55.32.251;
    set_real_ip_from 10.55.32.248;
    set_real_ip_from 10.4.22.238;
    set_real_ip_from 10.4.28.241;
    set_real_ip_from 10.55.28.240;
    set_real_ip_from 10.55.32.249; 

    real_ip_header   X-Forwarded-For;
    real_ip_recursive on;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;



    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}