apiVersion: apps/v1
kind: Deployment
metadata:
  name: bkextest
spec:
  selector:
    matchLabels:
      app: bkextest
  replicas: 1
  template:
    metadata:
      labels:
        app: bkextest
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "cp /tmp/index.html /usr/share/nginx/html/index.html"]
        volumeMounts:
          - name: bkextest
            mountPath: /usr/share/nginx/html
        resources:
          requests:
            cpu: 100m
            memory: "128M"
          limits:
            cpu: 100m
            memory: "256M"
      containers:
      - name: bkextest
        image: harbor.cis-qas.brown.edu/bkextest/bkextest:latest
        imagePullPolicy: Always    
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: bkextest
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            cpu: 100m
            memory: "128M"
          limits:
            cpu: 100m
            memory: "256M"
      volumes:
      - name: bkextest
        persistentVolumeClaim:
          claimName: bkextest
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
