apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bkeidrtest-vo
  namespace: cert-manager
spec:
  secretName: bkeidrtest-tls
  issuerRef:
    name: bke-ci-eab
    kind: ClusterIssuer
  commonName: drbkeitest.virtorch.brown.edu
  dnsNames:
  - drbkeitest.virtorch.brown.edu
