name: DEV deploy of bkeXtest services
on:
  push:
    branches:
      dev
env:
  DBKPI_KUBECONF: ${{ secrets.DBKPI_KUBECONF }}
  DBKPD_KUBECONF: ${{ secrets.DBKPD_KUBECONF }}
  ROBOT_DEV: ${{ secrets.ROBOT_DEV }}
    
jobs:
  Delete_and_Deploy_bkeXtest:
    runs-on: dev-ghrunner
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      -
        name: Get kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.22.0
      -
        name: pull kubeconfig
        run: |
          mkdir secrets
          touch secrets/dev-bkpi.yaml
          touch secrets/dev-bkpd.yaml
          touch secrets/robot-dev.txt
          echo "$DBKPI_KUBECONF" > secrets/dev-bkpi.yaml
          echo "$DBKPD_KUBECONF" > secrets/dev-bkpd.yaml
          echo "$ROBOT_DEV" > secrets/robot-dev.txt
      -
        name: Build
        run: make build
      -
        name: Push
        run: make push.dev
      -
        name: Delete
        run: make delete.dev
      -
        name: Deploy
        run: make deploy.dev