name: DEV deploy of bkeXtest services
on:
  push:
    branches:
      dev
env:
  DBKEI_KUBECONF: ${{ secrets.DBKEI_KUBECONF }}
  DBKED_KUBECONF: ${{ secrets.DBKED_KUBECONF }}
  ROBOT_DEV: ${{ secrets.ROBOT_DEV }}
    
jobs:
  Delete_and_Deploy_bkeXtest:
    runs-on: [self-hosted, qa-ghrunner]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      -
        name: Get kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.26.0
      -
        name: pull kubeconfig
        run: |
          mkdir secrets
          touch secrets/dev-bkei.yaml
          touch secrets/dev-bked.yaml
          touch secrets/robot-dev.txt
          echo "$DBKEI_KUBECONF" > secrets/dev-bkei.yaml
          echo "$DBKED_KUBECONF" > secrets/dev-bked.yaml
          echo "$ROBOT_DEV" > secrets/robot-dev.txt
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      -
        name: Build
        run: make build
      -
        name: Push
        run: make push.dev
      -
        name: Delete
        run: make delete.dev
      -
        name: Deploy
        run: make deploy.dev