name: DR build and deploy of bkeXtest services
on:
  release:
    types: [released]
env:
  DRBKPI_KUBECONF: ${{ secrets.DRBKPI_KUBECONF }}
  DRBKPD_KUBECONF: ${{ secrets.DRBKPD_KUBECONF }}
  ROBOT_DR: ${{ secrets.ROBOT_DR }}
    
jobs:
  Building_and_Deploying_bkeXtest:
    runs-on: [self-hosted, ghrunner]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      -
        name: Get kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.22.0
      -
        name: pull kubeconfig
        run: |
          touch files/bkpidr.yaml
          touch files/bkpddr.yaml
          touch files/robot.dr
          echo "$DRBKPI_KUBECONF" > files/bkpidr.yaml
          echo "$DRBKPD_KUBECONF" > files/bkpddr.yaml
          echo "$ROBOT_DR" > files/robot.dr
      -
        name: Build
        run: make build
      -
        name: Push
        run: make push.dr
      -
        name: Delete
        run: make delete.dr
      -
        name: Deploy
        run: make deploy.dr