name: DR build and deploy of bkeXtest services
on:
  release:
    types: [released]
env:
  DRBKEI_KUBECONF: ${{ secrets.DRBKEI_KUBECONF }}
  DRBKED_KUBECONF: ${{ secrets.DRBKED_KUBECONF }}
  DR_XTEST_ROBOT: ${{ secrets.DR_XTEST_ROBOT }}
    
jobs:
  Building_and_Deploying_bkeXtest:
    runs-on: [self-hosted, ghrunner]
    steps:
      -
        name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      -
        name: Get kubectl
        uses: azure/setup-kubectl@901a10e89ea615cf61f57ac05cecdf23e7de06d8
        with:
          version: v1.26.0
      -
        name: pull kubeconfig
        run: |
          mkdir secrets
          touch secrets/dr-bkei.yaml
          touch secrets/dr-bked.yaml
          touch secrets/robot-dr.txt
          echo "$DRBKEI_KUBECONF" > secrets/dr-bkei.yaml
          echo "$DRBKED_KUBECONF" > secrets/dr-bked.yaml
          echo "$DR_XTEST_ROBOT" > secrets/robot-dr.txt
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f
        with:
          install: true
      -
        name: Build
        run: make build
      -
        name: Push
        run: make push.dr
      -
        name: Delete
        run: make delete.dr
      -
        name: Deploy
        run: make deploy.dr