name: DR build and deploy of bkeXtest services
on:
  release:
    types: [released]
env:
  DRBKEI_KUBECONF: ${{ secrets.DRBKEI_KUBECONF }}
  DRBKED_KUBECONF: ${{ secrets.DRBKED_KUBECONF }}
  ROBOT_DR: ${{ secrets.ROBOT_DR }}
    
jobs:
  Building_and_Deploying_bkeXtest:
    runs-on: [self-hosted, ghrunner]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      -
        name: Get kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.26.0
      -
        name: pull kubeconfig
        run: |
          mkdir secrets
          touch secrets/dr-bkei.yaml
          touch secrets/dr-bked.yaml
          touch secrets/robot-dr.txt
          echo "$DRBKEI_KUBECONF" > secrets/dr-bkei.yaml
          echo "$DRBKED_KUBECONF" > secrets/dr-bked.yaml
          echo "$ROBOT_DR" > secrets/robot-dr.txt
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      -
        name: Build
        run: make build
      -
        name: Push
        run: make push.dr
      -
        name: Delete
        run: make delete.dr
      -
        name: Deploy
        run: make deploy.dr