name: DR build and deploy of bkeXtest services
on:
  release:
    types: [released]
    
jobs:
  Building_and_Deploying_bkeXtest:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      -
        name: Get kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.20.0
      -
        name: Build
        run: make build
      -
        name: Push
        run: make push.dr
      -
        name: Delete
        run: make delete.dr
      -
        name: Deploy
        run: make deploy.dr