name: PROD build and deploy of bkeXtest services
on:
  release:
    types: [released]
env:
  PBKPI_KUBECONF: ${{ secrets.PBKPI_KUBECONF }}
  PBKPD_KUBECONF: ${{ secrets.PBKPD_KUBECONF }}
  ROBOT_PROD: ${{ secrets.ROBOT_PROD }}
    
jobs:
  Building_and_Deploying_bkeXtest:
    runs-on: [self-hosted, ghrunner]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      -
        name: Get kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.22.0
      -
        name: pull kubeconfig
        run: |
          mkdir files
          touch files/bkpi.yaml
          touch files/bkpd.yaml
          touch files/robot.prod
          echo "$PBKPI_KUBECONF" > files/bkpi.yaml
          echo "$PBKPD_KUBECONF" > files/bkpd.yaml
          echo "$ROBOT_PROD" > files/robot.PROD
      -
        name: Build
        run: make build
      -
        name: Push
        run: make push.prod
      -
        name: Delete
        run: make delete.prod
      -
        name: Deploy
        run: make deploy.prod