name: PROD build and deploy of bkeXtest services
on:
  release:
    types: [released]
env:
  PBKEI_KUBECONF: ${{ secrets.PBKEI_KUBECONF }}
  PBKED_KUBECONF: ${{ secrets.PBKED_KUBECONF }}
  ROBOT_PROD: ${{ secrets.ROBOT_PROD }}
    
jobs:
  Building_and_Deploying_bkeXtest:
    runs-on: [self-hosted, ghrunner]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      -
        name: Get kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.26.0
      -
        name: pull kubeconfig
        run: |
          mkdir secrets
          touch secrets/prod-bkei.yaml
          touch secrets/prod-bked.yaml
          touch secrets/robot-prod.txt
          echo "$PBKEI_KUBECONF" > secrets/prod-bkei.yaml
          echo "$PBKED_KUBECONF" > secrets/prod-bked.yaml
          echo "$ROBOT_PROD" > secrets/robot-prod.txt
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      -
        name: Build
        run: make build
      -
        name: Push
        run: make push.prod
      -
        name: Delete
        run: make delete.prod
      -
        name: Deploy
        run: make deploy.prod