name: QA build and deploy of bkeXtest services
on:
  push:
    branches:
      dev
    
jobs:
  Building_and_Deploying_bkeXtest:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      -
        name: Get kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: v1.20.0
      -
        name: Build
        run: make build
      -
        name: Push
        run: make push-qa
      -
        name: Delete
        run: make delete-qa
      -
        name: Deploy
        run: make deploy-qa