name: QA build and deploy of bkeXtest services
on:
  push:
    branches:
      qa
env:
  QBKPI_KUBECONF: ${{ secrets.QBKPI_KUBECONF }}
  QBKPD_KUBECONF: ${{ secrets.QBKPD_KUBECONF }}
  ROBOT_QA: ${{ secrets.ROBOT_QA }}

jobs:
  Building_and_Deploying_bkeXtest:
    runs-on: [self-hosted, qa-ghrunner]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      -
        name: Get kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.22.0
      -
        name: pull kubeconfig
        run: |
          touch files/qa-bkpi.yaml
          touch files/qa-bkpd.yaml
          touch files/robot.qa
          echo "$QBKPI_KUBECONF" > files/qa-bkpi.yaml
          echo "$QBKPD_KUBECONF" > files/qa-bkpd.yaml
          echo "$ROBOT_QA" > files/robot.qa
      -
        name: Build
        run: make build
      -
        name: Push
        run: make push.qa
      -
        name: Delete
        run: make delete.qa
      -
        name: Deploy
        run: make deploy.qa