apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bkedtest-vo
  namespace: cert-manager
spec:
  secretName: bkedtest-tls
  issuerRef:
    name: bke-ci-eab
    kind: ClusterIssuer
  commonName: bkedtest.virtorch.brown.edu
  dnsNames:
  - bkedtest.virtorch.brown.edu
